# Generated by Django 3.2.9 on 2022-02-20 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Best_selling_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_photo', models.ImageField(upload_to='media')),
                ('product_name', models.CharField(blank=True, max_length=30, null=True)),
                ('product_details', models.CharField(blank=True, max_length=150, null=True)),
                ('product_price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billing_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=50)),
                ('apartment', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='media')),
                ('date', models.CharField(max_length=10)),
                ('writer', models.CharField(max_length=15)),
                ('blog_heading', models.CharField(max_length=30)),
                ('blog_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=30, null=True)),
                ('l_name', models.CharField(blank=True, max_length=30, null=True)),
                ('text_date', models.CharField(blank=True, max_length=20, null=True)),
                ('t_time', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_text', models.CharField(blank=True, max_length=12, null=True)),
                ('booking_message', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=1)),
                ('total', models.FloatField(default=0)),
                ('item_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Item_description', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='CartSubTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField(default=0)),
                ('delivery', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('Total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_saying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=500)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_profession', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=15, null=True)),
                ('address_details', models.CharField(blank=True, max_length=50, null=True)),
                ('opening_date', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discover_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_detail', models.CharField(blank=True, max_length=300, null=True)),
                ('menu1', models.ImageField(upload_to='media')),
                ('menu2', models.ImageField(upload_to='media')),
                ('menu3', models.ImageField(upload_to='media')),
                ('menu4', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Discover_story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Our_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service1_heading', models.CharField(blank=True, max_length=20, null=True)),
                ('service1_description', models.CharField(blank=True, max_length=100, null=True)),
                ('service2_heading', models.CharField(blank=True, max_length=20, null=True)),
                ('service2_description', models.CharField(blank=True, max_length=100, null=True)),
                ('service3_heading', models.CharField(blank=True, max_length=20, null=True)),
                ('service3_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temp_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coffeshop_App.best_selling_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
